
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// COURSE
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const LIST_COURSE_SUCCESS = "LIST_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";

// EXAM
export const CREATE_EXAM_SUCCESS = "CREATE_EXAM_SUCCESS";
export const DELETE_EXAM_SUCCESS = "DELETE_EXAM_SUCCESS";
export const FINDBY_COURSE_EXAM_SUCCESS = "FINDBY_COURSE_EXAM_SUCCESS";
export const FINDBY_STUDENT_EXAM_SUCCESS = "FINDBY_STUDENT_EXAM_SUCCESS";
export const FINDBY_TEACHER_EXAM_SUCCESS = "FINDBY_TEACHER_EXAM_SUCCESS";
export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";
export const LIST_EXAM_SUCCESS = "LIST_EXAM_SUCCESS";
export const UPDATE_EXAM_SUCCESS = "UPDATE_EXAM_SUCCESS";
export const VALIDATE_EXAM_SUCCESS = "VALIDATE_EXAM_SUCCESS";

// STUDENT
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const FINDBY_COURSES_STUDENT_SUCCESS = "FINDBY_COURSES_STUDENT_SUCCESS";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const LIST_STUDENT_SUCCESS = "LIST_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";

// TEACHER
export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const FINDBY_COURSES_TEACHER_SUCCESS = "FINDBY_COURSES_TEACHER_SUCCESS";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const LIST_TEACHER_SUCCESS = "LIST_TEACHER_SUCCESS";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
